### ISSUE TITLE
non-standard /Schemas endpoint

### ISSUE THREAD

**Issue by gsar** [RIPAGlobal/scimitar#117]
The SCIM RFC requires the [`/Schemas` endpoint](https://www.rfc-editor.org/rfc/rfc7644#section-4) to respond with a ListResponse format, but we seem to be returning just a plain JSON array in the result. This makes it impossible to auto-discover the schema on systems like Microsoft Entra. Looks like the code needs to wrap the array in a ListResponse structure.

**Comment by pond** [comment]
https://github.com/RIPAGlobal/scimitar/pull/133
