### ISSUE TITLE
omit Groups from /Schemas if not configured

### ISSUE THREAD

**Issue by gsar** [RIPAGlobal/scimitar#118]
I noticed the `/Schemas` endpoint always returns `Group` even though we don't have groups defined in our set up. Allowing `default_resources` to be configurable / overridable (or even determining this automatically from the fact that there is no groups resource included via the resources mixin) is a good idea to allow auto-discovery.

**Comment by pond** [comment]
https://github.com/RIPAGlobal/scimitar/pull/133

**Comment by pond** [comment]
Published as [v2.9.0](https://rubygems.org/gems/scimitar/versions/2.9.0) (Rails 7) and [v1.10.0](https://rubygems.org/gems/scimitar/versions/1.10.0) (Rails 6).
