### ISSUE TITLE
/Schemas reports unconfigured attributes

### ISSUE THREAD

**Issue by gsar** [RIPAGlobal/scimitar#120]
Our `scim_attributes_map` doesn't include attributes like `ims` but the output of `/Schemas` seems to include the full laundry list of attributes that could be configured. This makes auto-discovery not work properly.

**Comment by pond** [comment]
Fixed via [v2.9.0](https://rubygems.org/gems/scimitar/versions/2.9.0) (Rails 7) and [v1.10.0](https://rubygems.org/gems/scimitar/versions/1.10.0) (Rails 6).
