### ISSUE TITLE
Some error responses do not meet SCIM specification out of the box

### ISSUE THREAD

**Issue by spryffee** [RIPAGlobal/scimitar#124]
Hi! Thank you for this gem.

According to README, scimitar under the hood generates appropriate SCIM error response when it occurs. It is true for 404 on resources but if you add uniqueness validation it renders _{:error=>"Conflict", :status=>"409"}_ instead of SCIM compliant JSON. Should I overwrite _save!_ method to render proper error response or what is expected? Same applies to 401, it renders _{:error=>"Unauthorized", :status=>"401"}_ when token_authenticator returns false.

I'm using scimitar v2.7 and samples from the repo

**Comment by spryffee** [comment]
Sorry, the issue is invalid. This was due to some changes in forked repo on my side

**Comment by pond** [comment]
@spryffee For once, my workload and procrastination that delay me getting back to dealing with Scimitar issues pays dividends! :joy:

Glad you figured it out.
