### ISSUE TITLE
A record with a bigint `id` can't be queried for when using PostgreSQL

### ISSUE THREAD

**Issue by gyfis** [RIPAGlobal/scimitar#36]
We're using our bigint record IDs in the `self.scim_attributes_map`, e.g.

```
def self.scim_attributes_map
  {
    id: :id,

...

  }
end
```

however, when querying for the `id`, since by default all attributes are queried as case insensitive, we're getting a query like

```
WHERE users.id ILIKE 12345
```

which fails on PostgreSQL, since you can't use LIKE/ILIKE on bigint columns, and `id` is bigint for us.

I've read the source code and see the comments about case sensitivity being tricky to use, however I can't see a way of configuring this, and the only way I see is to subclass & override either `apply_scim_filter` or `to_activerecord_query_backend` methods fully. Is that the expected way forward?

I can see Scimitar exposing a `self.case_sensitive_attributes` map, empty by default, which would then be used to change the queries. Should I fire a PR with that?

**Comment by acceptto-nhumble** [comment]
This also fails for `uuid` type columns.

**Comment by pond** [comment]
Just got back to work after holidays - I'm considering options for it.

**Comment by pond** [comment]
I think this should be sorted in V2 by https://github.com/RIPAGlobal/scimitar/pull/39. Once reviewed & merged, this should get back-ported to V1. We have some people off sick right now so it might take a day or three - please bear with us!

**Comment by pond** [comment]
2.1.3 is now pushed - https://rubygems.org/gems/scimitar

**Comment by pond** [comment]
1.3.3 back-port done - https://rubygems.org/gems/scimitar/versions/1.3.3
