### ISSUE TITLE
Attribute names in filters are still case-sensitive

### ISSUE THREAD

**Issue by acceptto-nhumble** [RIPAGlobal/scimitar#37]
When processing the `filter` parameter, attribute names are looked up in a case-sensitive way. For example if I query `/scim/Users?filter=emails%20co%20nhumble` it works, but `/scim/Users?filter=Emails%20co%20nhumble` gives an invalid filter error.

The operators are properly case-insensitive, but the attribute names are not.

**Comment by pond** [comment]
Thanks. This should be fixed in V2 by #38 which, once reviewed & merged, will get back-ported to V1. We have some people off sick right now so it might take a day or three - please bear with us!

**Comment by pond** [comment]
2.1.3 is now pushed - https://rubygems.org/gems/scimitar

**Comment by pond** [comment]
1.3.3 back-port done - https://rubygems.org/gems/scimitar/versions/1.3.3
