### ISSUE TITLE
Parser.to_activerecord_query gives a TypeError on parsing filters

### ISSUE THREAD

**Issue by osingaatje** [RIPAGlobal/scimitar#72]
When trying to query for, say, 'emails eq "<email>"', the parser gives a TypeError

My code:
![My code](https://github.com/RIPAGlobal/scimitar/assets/46380170/332666ec-1c9d-4359-8def-42f6044c7538)

My test case and results:
![Debug session](https://github.com/RIPAGlobal/scimitar/assets/46380170/ccd650a2-463e-4013-af50-1e2a5c0a6d77)

Source code where shit hits the fan:
![Source code for the broken function](https://github.com/RIPAGlobal/scimitar/assets/46380170/ca82eb5c-f7e4-4065-9e5d-a3a2b45ac4fb)

**Comment by rjclaasen** [comment]
I ran into the same error message, and on my side it turned out to be an incorrectly configured `queryable_attributes` on the `CompanyUser` model.

Could you share your `CompanyUser` configuration? Especially the `queryable_attributes` part.

My changes:

```ruby
### user.rb -- before

def User
  ..
  
  self.scim_queryable_attributes
    { displayName: :display_name }
  end
```
to
```ruby
### user.rb -- after

def User
  ..

  self.scim_queryable_attributes
    { displayName: { column: :display_name } }
  end
```

**Comment by osingaatje** [comment]
EDIT: Nevermind, turns out .email is a function in my model

**Comment by osingaatje** [comment]
Yep :)
