### ISSUE TITLE
Schemas::Base not recognising complex attributes from extended schemas

### ISSUE THREAD

**Issue by osingaatje** [RIPAGlobal/scimitar#76]
When extending a Schema (in my case 'Group'), I got the problem where I _could_ convert my ActiveRecord model into Scim successfully, but when parsing a Scim Hash, the extended attribute did not get parsed properly.

A view of a debugging session inside `app/models/scimitar/resources/base.rb` (bug is in function `complex_scim_attributes`)
![bug-console-view](https://github.com/RIPAGlobal/scimitar/assets/46380170/92043311-9efc-421e-8da3-6395506c179d)

As you can see, `self.class.complex_scim_attributes` does **not** produce the same result as manually referring to the schema and doing the flat map etc. inside the class itself.

For reference, the extended attribute code (Team.rb not shown, but has `include Scim::TeamConcern`):

TeamConcern:
```ruby
module Scim
  module TeamConcern
    extend ActiveSupport::Concern

    class_methods do
      def scim_resource_type
        Scimitar::Resources::Group
      end

      def scim_attributes_map
        {
          id: :id,
          displayName: :name,
          members: [
            {
              list: :members,
              using: {
                value: :id,
                display: :full_name
              }
            }
          ],

          # Custom part of protocol: team leaders
          leaders: [
            {
              list: :leaders,
              using: {
                value: :id,
                display: :full_name
              }
            }
          ]
        }
      end

      def scim_mutable_attributes
        nil
      end

      def scim_queryable_attributes
        {
          displayName: :name
        }
      end

      def scim_timestamps_map
        {
          created: :created_at,
          lastModified: :updated_at
        }
      end
    end

    included do
      include Scimitar::Resources::Mixin
    end
  end
end
```

GroupLeaderExtension:
```ruby
module Scim
  module Extensions
    class GroupLeaderExtension < Scimitar::Schema::Base
      def initialize(_options = {})
        super(
          name: 'GroupLeaderExtension',
          description: 'Extension that adds a list of team leaders per Group',
          id: self.class.id,
          attributes: self.class.scim_attributes
        )
      end

      def self.id
        'urn:ietf:params:scim:schemas:extension:2.0:ozone:GroupLeaderExtension'
      end

      def self.scim_attributes
        [Scimitar::Schema::Attribute.new(multiValued: true, required: true, name: 'leaders', complexType: Scimitar::ComplexTypes::ReferenceMember)]
      end
    end
  end
end
```

**Comment by pond** [comment]
I haven't dived into this too deep - as you can tell from the slow response, I'm a bit overloaded with other tasks - but we just pushed Scimitar 2.6 which did include some fixes for extension schemas. There's a small chance it might fix your issue (though if not, that's a shame but don't worry, I *will* get a look at this whenever I have time...)

**Comment by pond** [comment]
@osingaatje Can you please let me know if you still see this problem with v2.6.1?

**Comment by osingaatje** [comment]
I haven't used it yet, and the project I was working on that used Scimitar has been handed off to somebody else, I'll contact them and see if it's resolved

**Comment by sjoulbak** [comment]
Hey @pond! 👋  Thanks for the heads up. Like you, I'm also a bit overloaded with other tasks. I can't make promises, but I'll try take a look at it tomorrow

**Comment by pond** [comment]
Assuming fixed & closing this now - I can reopen if need be.
