### ISSUE TITLE
Question about default type in addresses

### ISSUE THREAD

**Issue by s-andringa** [RIPAGlobal/scimitar#87]
Hi @pond,

The address complex type's `type` sub-attribute's [default value is 'work'](https://github.com/RIPAGlobal/scimitar/blob/1faf52503fdd223e6581b78ee98c4f8d65349e01/app/models/scimitar/complex_types/address.rb#L14). This surprised me, as it is not a required sub-attribute. And no other complex types have defaults for their sub-attributes. In [this commit](https://github.com/RIPAGlobal/scimitar/commit/19bab37ac846d35eee943ab20fb563cdaa107a8a) some have been removed from other complex types. Could it be that the address complex type was missed and should also be cleared of this default?

Thanks.

**Comment by pond** [comment]
Yeah, I mean I'm a bit worried that this might constitute a breaking change for some clients but it's an odd default and given the commit you reference - and thank you very much for digging that up, super useful! - it does look like something that was overlooked.

**Comment by pond** [comment]
@s-andringa https://github.com/RIPAGlobal/scimitar/pull/92

**Comment by pond** [comment]
This is now in [v2.7.0](https://rubygems.org/gems/scimitar/versions/2.7.0).

**Comment by pond** [comment]
...and [v1.8.0](https://rubygems.org/gems/scimitar/versions/1.8.0).
