### ISSUE TITLE
Add support for selecting specific attributes

### ISSUE THREAD

**Issue by xjunior** [RIPAGlobal/scimitar#89]
The SCIM protocol allows users to select the attributes retrieved in a call (see [RFC 7644 / section-3.9](https://datatracker.ietf.org/doc/html/rfc7644#section-3.9)). This is not contemplated by SCIMitar, but is a great feature to reduce the traffic and processing of information.

**Comment by pond** [comment]
Sorry for the very long delay here - at long last, I merged that into a feature branch to play around with it, made a minor adjustment and the result is #127 - please could you take a look and review that to see if it meets your requirements?

**Comment by pond** [comment]
Fix released in https://rubygems.org/gems/scimitar/versions/2.8.0. I'll backport to V1 within a week or two.
